apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vod
  template:
    metadata:
      labels:
        app: vod
    spec:
      containers:
      - name: vod
        image: kaseykim7123/24kng_web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "1"
        - name: SECRET_KEY
          value: "your_secret_key_here"
        - name: DB_NAME
          value: "project_24kng"
        - name: DB_USER
          value: "projectadmin"
        - name: DB_PASSWORD
          value: "projectuserpassword"
        - name: DB_HOST
          value: "3.36.115.185"
        - name: DB_PORT
          value: "3306"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
