apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-app
  template:
    metadata:
      labels:
        app: streaming-app
    spec:
      containers:
      - name: streaming-app
        image: kaseykim7123/24kng_webpages:e125ce9d65424a39f3717cc53138bd59d28f51c9
        ports:
        - containerPort: 8000

