apiVersion: v1
kind: Service
metadata:
  name: streaming-app-service
spec:
  selector:
    app: streaming-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streaming-app-service-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"  
spec:
  tls:
  - hosts:
    - fun.24kng.fun
    secretName: fun-24kn-fun-tls
  rules:
  - host: fun.24kng.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streaming-app-service
            port:
              number: 80

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vxztu2@naver.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
