apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streaming-app
  template:
    metadata:
      labels:
        app: streaming-app
    spec:
      containers:
      - name: streaming-app
        image: kaseykim7123/24kng_webpages:2d6ab363549a0733a24506aaeb54ee5f7c0b4e4a
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: streaming-app-service
spec:
  selector:
    app: streaming-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer