apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streaming-app
  template:
    metadata:
      labels:
        app: streaming-app
    spec:
      containers:
      - name: streaming-app
        image: kaseykim7123/24kng_webpages:294c6d6655aceb3887d08104fc58205a8eaf489d
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: streaming-app-service
spec:
  selector:
    app: streaming-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer